DROP TABLE IF EXISTS MED_DATA_DEIDENTIFIED CASCADE;

DROP TABLE IF EXISTS WORK_DATA CASCADE;

DROP TABLE IF EXISTS MED_DATA CASCADE;

CREATE TABLE MED_DATA_DEIDENTIFIED (
    ID TEXT PRIMARY KEY,
    AGE VARCHAR(20),
    GENDER VARCHAR(20),
    POSTAL_CODE VARCHAR(20),
    DIAGNOSIS VARCHAR(20)
);

CREATE TABLE WORK_DATA (
    ID SERIAL PRIMARY KEY,
    F_NAME VARCHAR(50),
    L_NAME VARCHAR(50),
    POSTAL_CODE VARCHAR(20),
    GENDER VARCHAR(20),
    EDUCATION VARCHAR(100),
    WORKPLACE VARCHAR(100),
    DEPARTMENT VARCHAR(50)
);

CREATE TABLE MED_DATA (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(50),
    AGE INTEGER,
    ADDRESS VARCHAR(100),
    EMAIL VARCHAR(50),
    GENDER VARCHAR(20),
    POSTAL_CODE VARCHAR(20),
    DIAGNOSIS VARCHAR(20)
);